// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency">> = Specific
  const handler = {} as typeof import("../../src/app/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/analytics-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics-lab">> = Specific
  const handler = {} as typeof import("../../src/app/analytics-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/chat/[conversationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/chat/[conversationId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/chat/[conversationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/content">> = Specific
  const handler = {} as typeof import("../../src/app/app/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/library">> = Specific
  const handler = {} as typeof import("../../src/app/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/seo">> = Specific
  const handler = {} as typeof import("../../src/app/app/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/social/connected/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/social/connected">> = Specific
  const handler = {} as typeof import("../../src/app/app/social/connected/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/social">> = Specific
  const handler = {} as typeof import("../../src/app/app/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/audience-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audience-lab">> = Specific
  const handler = {} as typeof import("../../src/app/audience-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/autopilot-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/autopilot-lab">> = Specific
  const handler = {} as typeof import("../../src/app/autopilot-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/brain-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brain-lab">> = Specific
  const handler = {} as typeof import("../../src/app/brain-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar-lab">> = Specific
  const handler = {} as typeof import("../../src/app/calendar-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-lab">> = Specific
  const handler = {} as typeof import("../../src/app/chat-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content">> = Specific
  const handler = {} as typeof import("../../src/app/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/canva/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/canva/callback">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/canva/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/github/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/github/callback">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/github/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/google/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/google/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/notion/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/notion/result">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/notion/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/webflow/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/webflow/callback">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/webflow/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integrations/wordpress/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/wordpress/callback">> = Specific
  const handler = {} as typeof import("../../src/app/integrations/wordpress/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../src/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/links-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/links-lab">> = Specific
  const handler = {} as typeof import("../../src/app/links-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/oauth/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oauth/consent">> = Specific
  const handler = {} as typeof import("../../src/app/oauth/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/share/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/share/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studio-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio-lab">> = Specific
  const handler = {} as typeof import("../../src/app/studio-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/audience/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/audience">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/audience/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/autopilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/autopilot">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/autopilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/backlinks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/backlinks">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/backlinks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/brain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/brain">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/brain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/brand-kit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/brand-kit">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/brand-kit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/chat/[conversationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/chat/[conversationId]">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/chat/[conversationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/competitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/competitors">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/competitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/experiments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app/experiments">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/experiments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/app">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/w/[workspaceId]">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces">> = Specific
  const handler = {} as typeof import("../../src/app/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/.well-known/oauth-protected-resource/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/oauth-protected-resource/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/.well-known/oauth-protected-resource/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/enforcement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/enforcement">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/enforcement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/manage">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/findings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/findings">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/findings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/runs">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/library">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/persist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/persist">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/persist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/addons/change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/addons/change">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/addons/change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/addons/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/addons/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/addons/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/brands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/brands">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/brands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/entitlements">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/subscription/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/subscription/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/subscription/change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription/change">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/subscription/change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/subscription/pause/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription/pause">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/subscription/pause/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/subscription/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/subscription/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/subscription/resume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/subscription/resume">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/subscription/resume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/upgrade-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/upgrade-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/upgrade-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/wallet">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/brand-extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brand-extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/brand-extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clarify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clarify">> = Specific
  const handler = {} as typeof import("../../src/app/api/clarify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/client-errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-errors">> = Specific
  const handler = {} as typeof import("../../src/app/api/client-errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/file-extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/file-extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/file-extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-video">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/scans/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/scans/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/scans/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/scans/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/scans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/scans/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geo/scans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geo/scans">> = Specific
  const handler = {} as typeof import("../../src/app/api/geo/scans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/canva/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/canva/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/canva/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/canva/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/canva/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/canva/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/github/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/github/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/github/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/github/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/notion/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/notion/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/notion/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/notion/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/notion/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/notion/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/webflow/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/webflow/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/webflow/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/wordpress/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/wordpress/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/wordpress/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/latest">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/trends">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../src/app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/memory-extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory-extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/memory-extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pexels/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pexels/video">> = Specific
  const handler = {} as typeof import("../../src/app/api/pexels/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/agents-tick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/agents-tick">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/agents-tick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/analytics-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/analytics-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/analytics-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/competitor-watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/competitor-watch">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/competitor-watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/experiments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/experiments">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/experiments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/geo-agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/geo-agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/geo-agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/geo-scans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/geo-scans">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/geo-scans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/kie/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/kie">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/kie/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/link-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/link-catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/link-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/link-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/link-orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/link-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/openrouter-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/openrouter-video">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/openrouter-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/ops-watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/ops-watch">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/ops-watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/postforme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/postforme">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/postforme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/run-schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/run-schedules">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/run-schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/sdr-reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/sdr-reconcile">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/sdr-reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/sdr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/sdr">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/sdr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/socialapi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/socialapi">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/socialapi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/hooks/ugc-renders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/hooks/ugc-renders">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/hooks/ugc-renders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/share/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/share/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/share/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rpc/[...fn]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc/[...fn]">> = Specific
  const handler = {} as typeof import("../../src/app/api/rpc/[...fn]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/publications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/publications">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/publications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sdr/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sdr/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/sdr/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shares">> = Specific
  const handler = {} as typeof import("../../src/app/api/shares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social-multi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-multi">> = Specific
  const handler = {} as typeof import("../../src/app/api/social-multi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/connect/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/connect/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/connect/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/connect/postforme/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/connect/postforme/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/connect/postforme/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/connect/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/connect/select">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/connect/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/creator-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/creator-info">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/creator-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/metrics/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/metrics/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/metrics/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/social/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/ideas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/ideas">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/ideas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/prompt">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/studio/upload-captions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio/upload-captions">> = Specific
  const handler = {} as typeof import("../../src/app/api/studio/upload-captions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/models">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/products/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/products/extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/products/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/projects/[id]/concepts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/projects/[id]/concepts">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/projects/[id]/concepts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/projects/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/projects/[id]/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/projects/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/references/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/references/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/references/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/references/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/references/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/references/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/renders/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/renders/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/renders/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/renders/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/renders/[id]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/renders/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/renders/[id]/post-draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/renders/[id]/post-draft">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/renders/[id]/post-draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/renders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/renders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/renders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ugc/renders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ugc/renders">> = Specific
  const handler = {} as typeof import("../../src/app/api/ugc/renders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/unsplash/random/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsplash/random">> = Specific
  const handler = {} as typeof import("../../src/app/api/unsplash/random/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health">> = Specific
  const handler = {} as typeof import("../../src/app/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/r/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/r/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/r/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/w/[workspaceId]/app">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/w/[workspaceId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/w/[workspaceId]">> = Specific
  const handler = {} as typeof import("../../src/app/w/[workspaceId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
