/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAgentTasksRouteImport } from './routes/api.agent-tasks'
import { Route as ApiAiGenerateRouteImport } from './routes/api.ai-generate'
import { Route as ApiBrandExtractRouteImport } from './routes/api.brand-extract'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiClarifyRouteImport } from './routes/api.clarify'
import { Route as ApiFileExtractRouteImport } from './routes/api.file-extract'
import { Route as ApiGenerateImageRouteImport } from './routes/api.generate-image'
import { Route as ApiGeoAuditRouteImport } from './routes/api.geo-audit'
import { Route as ApiMemoryExtractRouteImport } from './routes/api.memory-extract'
import { Route as ApiSharesRouteImport } from './routes/api.shares'
import { Route as ApiSocialMultiRouteImport } from './routes/api.social-multi'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppSeoRouteImport } from './routes/app.seo'
import { Route as AppSocialRouteImport } from './routes/app.social'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as ApiPublicHooksCompetitorWatchRouteImport } from './routes/api/public/hooks/competitor-watch'
import { Route as ApiPublicHooksRunSchedulesRouteImport } from './routes/api/public/hooks/run-schedules'
import { Route as ApiPublicShareSlugRouteImport } from './routes/api/public/share.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTasksRoute = ApiAgentTasksRouteImport.update({
  id: '/api/agent-tasks',
  path: '/api/agent-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai-generate',
  path: '/api/ai-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandExtractRoute = ApiBrandExtractRouteImport.update({
  id: '/api/brand-extract',
  path: '/api/brand-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClarifyRoute = ApiClarifyRouteImport.update({
  id: '/api/clarify',
  path: '/api/clarify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileExtractRoute = ApiFileExtractRouteImport.update({
  id: '/api/file-extract',
  path: '/api/file-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoAuditRoute = ApiGeoAuditRouteImport.update({
  id: '/api/geo-audit',
  path: '/api/geo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryExtractRoute = ApiMemoryExtractRouteImport.update({
  id: '/api/memory-extract',
  path: '/api/memory-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialMultiRoute = ApiSocialMultiRouteImport.update({
  id: '/api/social-multi',
  path: '/api/social-multi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCompetitorWatchRoute =
  ApiPublicHooksCompetitorWatchRouteImport.update({
    id: '/api/public/hooks/competitor-watch',
    path: '/api/public/hooks/competitor-watch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunSchedulesRoute =
  ApiPublicHooksRunSchedulesRouteImport.update({
    id: '/api/public/hooks/run-schedules',
    path: '/api/public/hooks/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShareSlugRoute = ApiPublicShareSlugRouteImport.update({
  id: '/api/public/share/$slug',
  path: '/api/public/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/agent-tasks': typeof ApiAgentTasksRoute
  '/api/ai-generate': typeof ApiAiGenerateRoute
  '/api/brand-extract': typeof ApiBrandExtractRoute
  '/api/chat': typeof ApiChatRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/file-extract': typeof ApiFileExtractRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/geo-audit': typeof ApiGeoAuditRoute
  '/api/memory-extract': typeof ApiMemoryExtractRoute
  '/api/shares': typeof ApiSharesRoute
  '/api/social-multi': typeof ApiSocialMultiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/content': typeof AppContentRoute
  '/app/seo': typeof AppSeoRoute
  '/app/social': typeof AppSocialRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$slug': typeof ShareSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/competitor-watch': typeof ApiPublicHooksCompetitorWatchRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/agent-tasks': typeof ApiAgentTasksRoute
  '/api/ai-generate': typeof ApiAiGenerateRoute
  '/api/brand-extract': typeof ApiBrandExtractRoute
  '/api/chat': typeof ApiChatRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/file-extract': typeof ApiFileExtractRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/geo-audit': typeof ApiGeoAuditRoute
  '/api/memory-extract': typeof ApiMemoryExtractRoute
  '/api/shares': typeof ApiSharesRoute
  '/api/social-multi': typeof ApiSocialMultiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/content': typeof AppContentRoute
  '/app/seo': typeof AppSeoRoute
  '/app/social': typeof AppSocialRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$slug': typeof ShareSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/competitor-watch': typeof ApiPublicHooksCompetitorWatchRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/agent-tasks': typeof ApiAgentTasksRoute
  '/api/ai-generate': typeof ApiAiGenerateRoute
  '/api/brand-extract': typeof ApiBrandExtractRoute
  '/api/chat': typeof ApiChatRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/file-extract': typeof ApiFileExtractRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/geo-audit': typeof ApiGeoAuditRoute
  '/api/memory-extract': typeof ApiMemoryExtractRoute
  '/api/shares': typeof ApiSharesRoute
  '/api/social-multi': typeof ApiSocialMultiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/content': typeof AppContentRoute
  '/app/seo': typeof AppSeoRoute
  '/app/social': typeof AppSocialRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$slug': typeof ShareSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/competitor-watch': typeof ApiPublicHooksCompetitorWatchRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/share/$slug': typeof ApiPublicShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/api/agent-tasks'
    | '/api/ai-generate'
    | '/api/brand-extract'
    | '/api/chat'
    | '/api/clarify'
    | '/api/file-extract'
    | '/api/generate-image'
    | '/api/geo-audit'
    | '/api/memory-extract'
    | '/api/shares'
    | '/api/social-multi'
    | '/app/analytics'
    | '/app/content'
    | '/app/seo'
    | '/app/social'
    | '/auth/callback'
    | '/share/$slug'
    | '/app/'
    | '/api/public/hooks/competitor-watch'
    | '/api/public/hooks/run-schedules'
    | '/api/public/share/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/api/agent-tasks'
    | '/api/ai-generate'
    | '/api/brand-extract'
    | '/api/chat'
    | '/api/clarify'
    | '/api/file-extract'
    | '/api/generate-image'
    | '/api/geo-audit'
    | '/api/memory-extract'
    | '/api/shares'
    | '/api/social-multi'
    | '/app/analytics'
    | '/app/content'
    | '/app/seo'
    | '/app/social'
    | '/auth/callback'
    | '/share/$slug'
    | '/app'
    | '/api/public/hooks/competitor-watch'
    | '/api/public/hooks/run-schedules'
    | '/api/public/share/$slug'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/api/agent-tasks'
    | '/api/ai-generate'
    | '/api/brand-extract'
    | '/api/chat'
    | '/api/clarify'
    | '/api/file-extract'
    | '/api/generate-image'
    | '/api/geo-audit'
    | '/api/memory-extract'
    | '/api/shares'
    | '/api/social-multi'
    | '/app/analytics'
    | '/app/content'
    | '/app/seo'
    | '/app/social'
    | '/auth/callback'
    | '/share/$slug'
    | '/app/'
    | '/api/public/hooks/competitor-watch'
    | '/api/public/hooks/run-schedules'
    | '/api/public/share/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAgentTasksRoute: typeof ApiAgentTasksRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiBrandExtractRoute: typeof ApiBrandExtractRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiClarifyRoute: typeof ApiClarifyRoute
  ApiFileExtractRoute: typeof ApiFileExtractRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGeoAuditRoute: typeof ApiGeoAuditRoute
  ApiMemoryExtractRoute: typeof ApiMemoryExtractRoute
  ApiSharesRoute: typeof ApiSharesRoute
  ApiSocialMultiRoute: typeof ApiSocialMultiRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiPublicHooksCompetitorWatchRoute: typeof ApiPublicHooksCompetitorWatchRoute
  ApiPublicHooksRunSchedulesRoute: typeof ApiPublicHooksRunSchedulesRoute
  ApiPublicShareSlugRoute: typeof ApiPublicShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-tasks': {
      id: '/api/agent-tasks'
      path: '/api/agent-tasks'
      fullPath: '/api/agent-tasks'
      preLoaderRoute: typeof ApiAgentTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-generate': {
      id: '/api/ai-generate'
      path: '/api/ai-generate'
      fullPath: '/api/ai-generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-extract': {
      id: '/api/brand-extract'
      path: '/api/brand-extract'
      fullPath: '/api/brand-extract'
      preLoaderRoute: typeof ApiBrandExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clarify': {
      id: '/api/clarify'
      path: '/api/clarify'
      fullPath: '/api/clarify'
      preLoaderRoute: typeof ApiClarifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-extract': {
      id: '/api/file-extract'
      path: '/api/file-extract'
      fullPath: '/api/file-extract'
      preLoaderRoute: typeof ApiFileExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo-audit': {
      id: '/api/geo-audit'
      path: '/api/geo-audit'
      fullPath: '/api/geo-audit'
      preLoaderRoute: typeof ApiGeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory-extract': {
      id: '/api/memory-extract'
      path: '/api/memory-extract'
      fullPath: '/api/memory-extract'
      preLoaderRoute: typeof ApiMemoryExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-multi': {
      id: '/api/social-multi'
      path: '/api/social-multi'
      fullPath: '/api/social-multi'
      preLoaderRoute: typeof ApiSocialMultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo': {
      id: '/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/social': {
      id: '/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/competitor-watch': {
      id: '/api/public/hooks/competitor-watch'
      path: '/api/public/hooks/competitor-watch'
      fullPath: '/api/public/hooks/competitor-watch'
      preLoaderRoute: typeof ApiPublicHooksCompetitorWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-schedules': {
      id: '/api/public/hooks/run-schedules'
      path: '/api/public/hooks/run-schedules'
      fullPath: '/api/public/hooks/run-schedules'
      preLoaderRoute: typeof ApiPublicHooksRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share/$slug': {
      id: '/api/public/share/$slug'
      path: '/api/public/share/$slug'
      fullPath: '/api/public/share/$slug'
      preLoaderRoute: typeof ApiPublicShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppContentRoute: typeof AppContentRoute
  AppSeoRoute: typeof AppSeoRoute
  AppSocialRoute: typeof AppSocialRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppContentRoute: AppContentRoute,
  AppSeoRoute: AppSeoRoute,
  AppSocialRoute: AppSocialRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAgentTasksRoute: ApiAgentTasksRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiBrandExtractRoute: ApiBrandExtractRoute,
  ApiChatRoute: ApiChatRoute,
  ApiClarifyRoute: ApiClarifyRoute,
  ApiFileExtractRoute: ApiFileExtractRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGeoAuditRoute: ApiGeoAuditRoute,
  ApiMemoryExtractRoute: ApiMemoryExtractRoute,
  ApiSharesRoute: ApiSharesRoute,
  ApiSocialMultiRoute: ApiSocialMultiRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiPublicHooksCompetitorWatchRoute: ApiPublicHooksCompetitorWatchRoute,
  ApiPublicHooksRunSchedulesRoute: ApiPublicHooksRunSchedulesRoute,
  ApiPublicShareSlugRoute: ApiPublicShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
